### PR TITLE
try to import synapse-react-client

### PR DESCRIPTION
**Pull request by inodb**
currently errors with global CSS cannot be imported from within
node_modules

### CODE REVIEW

**Comment by onursumer** [comment]
To fix the mismatching react versions the workaround is to add `resolutions` into `package.json`. Ideally the library should make `react` a peer dependency instead of a dependency.

```JavaScript
  "resolutions": {
    "synapse-react-client/react": "16.13.0"
  }
```

Some components have direct reference to the `window` object which causes issues for server side rendering. So, for example for the `Login` component, we need to disable server side rendering.

```JavaScript
const Login = dynamic(
    () => import('synapse-react-client/dist/containers/Login'),
    { ssr: false }
);
```

Not sure how to fix the global css reference issue but ideally the library itself should not have any reference to external global css files. Consumers of the library should include them explicitly.

**Comment by inodb** [comment]
@milen-sage Could you help loop in someone who can help address @onursumer's comments? Thanks!

**Comment by inodb** [comment]
It would be ideal if we can pull the package from npm as well (as im doing currently in this PR)

**Comment by inodb** [comment]
Closing this for now

**Pull request closed without merging**
