### PR TITLE
Add assets for 11 H&E images

### PR DESCRIPTION
**Pull request by adamjtaylor**

### CODE REVIEW

**Comment by inodb** [comment]
FYI:
```
./data/htan-imaging-assets.json
--
05:26:44.943 | Module parse failed: Unexpected string in JSON at position 70172 while parsing '[
05:26:44.944 | {
05:26:44.944 | "synid": "syn24829425",
05:26:44.944 | "m'
05:26:44.944 | You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
05:26:44.944 | SyntaxError: Unexpected string in JSON at position 70172 while parsing '

```

**Comment by adamjtaylor** [comment]
Thanks @inodb ... yeah a did something on my end that is introducing a bunch of conflicts. Looking into it this afternoon.

**Comment by inodb** [comment]
@adamjtaylor kinda missed this - should we close it?

**Comment by adamjtaylor** [comment]
@inodb we can close.

**Pull request closed without merging**
