### PR TITLE
Add IDC Linkouts

### PR DESCRIPTION
**Pull request by inodb**
Adds IDC Linkouts based on mappings provided by IDC

### Thumnbail with Minerva + IDC
Screen Shot 2022-08-08 at 12 00 02 PM

### Just IDC
Screen Shot 2022-08-08 at 12 02 04 PM

### Download text when clicking on a file
Screen Shot 2022-08-08 at 12 44 29 PM

## Notes

- ~Seems like Duke Images are missing~ Only HMS, OHSU and WashU are included in this release

### CODE REVIEW

**Comment by adamjtaylor** [comment]
@inodb We are only expecting IDC image links for HMS, OHSU and WASHU. Duke not included in this IDC release.

**Comment by adamjtaylor** [comment]
For the download text perhaps we could revise to something along the lines of

> "This image is available in DICOM format from Imaging Data Commons"

**Comment by adamjtaylor** [comment]
If we want to provide example BigQuery queries for individual series we can use the following

```{sql}
SELECT *
FROM
 `bigquery-public-data.idc_current.dicom_all` as dic_all
WHERE
 SeriesInstanceUID = '1.3.6.1.4.1.5962.99.1.2004400158.1892580498.1655566841886.4.0'
```

**Comment by fedorov** [comment]
> If we want to provide example BigQuery queries for individual series

@adamjtaylor if you could let me know what kind of questions would be relevant to have answered for the HTAN community, I can help with the queries. I can also provide the query that was used to generate the links, mapping those to the file/biospecimen IDs.

**Comment by fedorov** [comment]
Few comments:

* I do not see the IDC links in the preview site. I expected to see them when selecting OME-TIFF as file type, although there are extra questions about that further.
* wouldn't it be helpful to have some kind of a filter that would allow selecting just the files that are available for download?
* clicking on the file name leads to the popup below, which is not helpful at all, since it is not possible to select and download individual files in the IDC portal. What would be more helpful is a list of GCS URLs, or a selection query, and instructions on how to download those files (and/or a link to the IDC download instructions pagehttps://learn.canceridc.dev/data/downloading-data). I strongly encourage you to actually follow the download steps and confirm for yourself how download process works, so you know what is going on and better prepared to respond to user questions.
image
* We should think if/how it should be communicated to the users that the files available from IDC are not the same as those collected by HTAN. It is somewhat misleading to click on a file with .tif extension, and create impression that user can download **that** file form IDC - no, they can't! It should be somehow communicated that IDC has DICOM-TIFF files, which are discussed to some degree in this IDC doc article https://learn.canceridc.dev/dicom/dicom-tiff-dual-personality-files (if you have suggestions re level of details, please do let us know).

**Comment by adamjtaylor** [comment]
@fedorov re 
> I do not see the IDC links in the preview site. I expected to see them when selecting OME-TIFF as file type, although there are extra questions about that further.

I have added a quick screen recording showing where these links are (for those that have IDC-released images.

[image]((https://www.loom.com/share/7cdee3238df444b885ec3a176fd36cfb))

Agree with your other points and we can continue to discuss and amend

**Comment by fedorov** [comment]
Thank you Adam, this is very helpful! I personally think having those links in a tooltip over an image is quite obscure. Are there strong arguments against putting those links right under the image thumbnail in the search results table?

**Comment by adamjtaylor** [comment]
@fedorov I like your suggestion of links under the thumbnail

for example...


[View in Minerva](https://d3p249wtgzkn5u.cloudfront.net/synid/syn24829429/v1/minerva/index.html#s=0) | [View in IDC Slim](https://viewer.imaging.datacommons.cancer.gov/slim/studies/2.25.56219147941526607962658668060030231728/series/1.3.6.1.4.1.5962.99.1.2004400158.1892580498.1655566841886.4.0)

@inodb would this be possible?

**Comment by inodb** [comment]
Thanks so much for the feedback @fedorov and @adamjtaylor !

- I changed the download text to specify DICOM and mention the download page:
    Screen Shot 2022-08-10 at 1 13 36 PM
- I like the links below the thumbnail idea, but it might get kinda cluttered. Want to think about it some more before implementing

Are we ok with rolling this PR out as is and we can iterate further using the feedback you both provided? I filed a [ticket](https://github.com/ncihtan/htan-portal/issues/428)

**Comment by fedorov** [comment]
> I changed the download text to specify DICOM and mention the download page:

I am not sure this is sufficient. Given the file name in the popup, even I would have hard times figuring out how to download corresponding files. Can you include the list of GCS URLs corresponding to the matching DICOM data? We provided those to you in the spreadsheet I shared earlier.

Also, it would be good to change "DICOM format" to "DICOM-TIFF format", and hyperlink that to the page I shared about DICOM-TIFF. What do you think?

**Comment by inodb** [comment]
@fedorov that makes sense! Thank you! How is this:

Screen Shot 2022-08-10 at 6 57 37 PM

I just tried to download some imaging data and it worked like a charm 👍🏻

**Comment by inodb** [comment]
@fedorov I made a few more tweaks after realizing downloading is sponsored by Google 😮:
Screen Shot 2022-08-10 at 7 45 26 PM

**Comment by fedorov** [comment]
I have some hesitations about the 2nd paragraph - I am not sure we need it. If the user follows the instructions, it will not be applicable. But I can also see the point to play extra safe at the cost of making the instructions more confusing... I wonder what @wlongabaugh thinks about this, but I am afraid he is already out of office through the end of next week.

I think it is ok to merge this, and we can refine further later based on experience/feedback/discussions.

> I just tried to download some imaging data and it worked like a charm 👍🏻

Really appreciate you went through those steps!

**Comment by wlongabaugh** [comment]
I have not left town yet. If we are talking about the paragraph that discusses download costs, it looks like Ino based it on an explanation I gave him about these costs yesterday. I will point out that you need to provide a _separate_ project ID argument (**-u projectID**) to the gsutil command to have that project charged. That is, to my understanding, the gcloud project setting is _not_ used for that purpose, so you do not need to unset it. In my description yesterday, I pointed out that you _don't_ want to provide a -u argument with Google PDP, since then you are telling it you want to pay for something that is free. So by saying nothing about it at all, I think it will be free.

**Comment by inodb** [comment]
Thanks so much @wlongabaugh and @fedorov ! Appreciate all the quick feedback! Y'all are the best! I removed the 2nd paragraph re Google PDP. Will merge & deploy

**Pull request merged**
